# Generated by Django 5.1.2 on 2024-11-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_business_profile_rename_local_suppport_local_support_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
