# Generated by Django 5.1.2 on 2024-11-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0006_rename_form_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
