# Generated by Django 5.1.2 on 2024-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0008_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='dummy',
        ),
    ]
